name: Test Workflow

on:
  push:    # triggers on any commit
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run your email-named step
      - name: 23f2001635@ds.study.iitm.ac.in
        run: echo "Hello, world!"
